# Generated by Django 5.2.1 on 2025-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование ВУЗа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор'), ('university', 'ВУЗ')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
