# Generated by Django 5.2.1 on 2025-05-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('host_institution', models.CharField(max_length=255, verbose_name='Принимающее учреждение')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('application_deadline', models.DateField(verbose_name='Крайний срок подачи заявок')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('benefits', models.TextField(blank=True, verbose_name='Преимущества')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'программа мобильности',
                'verbose_name_plural': 'программы мобильности',
                'ordering': ['-application_deadline'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (месяцев)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'образовательная программа',
                'verbose_name_plural': 'образовательные программы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('journal_name', models.CharField(blank=True, max_length=255, verbose_name='Название журнала/издания')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Файл публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название аккредитации')),
                ('organization', models.CharField(max_length=255, verbose_name='Аккредитующая организация')),
                ('date_received', models.DateField(verbose_name='Дата получения')),
                ('expiration_date', models.DateField(verbose_name='Дата истечения')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Номер сертификата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='education.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'аккредитация',
                'verbose_name_plural': 'аккредитации',
                'ordering': ['-date_received'],
            },
        ),
    ]
