# Generated by Django 5.2.1 on 2025-05-27 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
    ]
